# -*- coding: utf-8 -*-
"""Task_3_Bank.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11adRHM6odL8nrVHjXKrAD2MM93LRD1n0
"""

class BankAccount:
    def __init__(self, account_holder, initial_balance=0):
        self.account_holder = account_holder
        self.balance = initial_balance

    def check_balance(self):
        return self.balance

    def deposit(self, amount):
        if amount > 0:
            self.balance += amount
            print(f"Deposited ₹{amount}. New balance: ₹{self.balance}")
            return True
        else:
            print("Invalid deposit amount. Please enter a positive value.")
            return False

    def withdraw(self, amount):
        if 0 < amount <= self.balance:
            self.balance -= amount
            print(f"Withdrew ₹{amount}. New balance: ₹{self.balance}")
            return True
        else:
            print("Invalid withdrawal amount or insufficient funds.")
            return False

#  Creating a bank account
account_holder_name = "Aanchal Jha"
initial_balance = 1890

aanchals_account = BankAccount(account_holder_name, initial_balance)

# Check initial balance
print(f"Initial balance for {aanchals_account.account_holder}: ₹{aanchals_account.check_balance()}")

# Deposit money
deposit_amount = 550
aanchals_account.deposit(deposit_amount)

# Withdraw money
withdrawal_amount = 260
aanchals_account.withdraw(withdrawal_amount)

