# -*- coding: utf-8 -*-
"""Task-2_alarmclock.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JXmKUnedXevFgd8sWqRjlD-1KVAkEvvs
"""

import datetime
import time  # Add this line
!pip install playsound
from playsound import playsound

def alarm(alarm_time):
    while True:
        current_time = datetime.datetime.now()
        if current_time.strftime("%H:%M") == alarm_time:
            playsound('alarm_sound.wav')
            print("Alarm ringing!")
            break
        time.sleep(1)

alarm_hour = input("Enter the hour (24-hour format): ")
alarm_minute = input("Enter the minute: ")

alarm_time = f"{alarm_hour}:{alarm_minute}"
print("Alarm set for:", alarm_time)

alarm(alarm_time)